-- Natasha schema, generated by scripts/generate_migrations.py - do not edit by hand.
-- Source of truth: the SCHEMA constant of each subsystem (see natasha.db.schema).

-- natasha.events.log
CREATE TABLE IF NOT EXISTS events (
    seq        INTEGER PRIMARY KEY AUTOINCREMENT,
    id         TEXT    NOT NULL UNIQUE,
    ts         TEXT    NOT NULL,
    kind       TEXT    NOT NULL,
    actor      TEXT    NOT NULL,
    source     TEXT    NOT NULL DEFAULT '',
    trace_id   TEXT    NOT NULL DEFAULT '',
    mission_id TEXT    NOT NULL DEFAULT '',
    parent_id  TEXT    NOT NULL DEFAULT '',
    risk       TEXT    NOT NULL DEFAULT 'NONE',
    payload    TEXT    NOT NULL DEFAULT '{}',
    prev_hash  TEXT    NOT NULL,
    hash       TEXT    NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_events_trace   ON events(trace_id);
CREATE INDEX IF NOT EXISTS idx_events_mission ON events(mission_id);
CREATE INDEX IF NOT EXISTS idx_events_kind    ON events(kind, seq);
CREATE INDEX IF NOT EXISTS idx_events_ts      ON events(ts);

CREATE TRIGGER IF NOT EXISTS events_append_only_update
BEFORE UPDATE ON events BEGIN
    SELECT RAISE(ABORT, 'event log is append-only: UPDATE rejected');
END;
CREATE TRIGGER IF NOT EXISTS events_append_only_delete
BEFORE DELETE ON events BEGIN
    SELECT RAISE(ABORT, 'event log is append-only: DELETE rejected');
END;

-- natasha.memory.store
CREATE TABLE IF NOT EXISTS memories (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    content TEXT NOT NULL,
    summary TEXT DEFAULT '',
    tags TEXT DEFAULT '[]',
    entities TEXT DEFAULT '[]',
    importance REAL DEFAULT 0.5,
    confidence REAL DEFAULT 0.8,
    retention TEXT DEFAULT 'long_term',
    provenance TEXT DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    last_accessed_at TEXT DEFAULT '',
    access_count INTEGER DEFAULT 0,
    expires_at TEXT DEFAULT '',
    pinned INTEGER DEFAULT 0,
    superseded_by TEXT DEFAULT '',
    embedding TEXT DEFAULT '[]',
    metadata TEXT DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_memories_kind ON memories(kind, created_at);
CREATE INDEX IF NOT EXISTS idx_memories_active ON memories(superseded_by) WHERE superseded_by = '';
CREATE TABLE IF NOT EXISTS memory_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    memory_id TEXT,
    action TEXT,
    detail TEXT,
    actor TEXT,
    at TEXT
);

-- natasha.missions.store
CREATE TABLE IF NOT EXISTS missions (
    id TEXT PRIMARY KEY,
    state TEXT NOT NULL,
    priority INTEGER DEFAULT 3,
    parent_id TEXT DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    started_at TEXT DEFAULT '',
    finished_at TEXT DEFAULT '',
    payload TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_missions_state ON missions(state, priority);

-- natasha.world.store
CREATE TABLE IF NOT EXISTS entities (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    name_key TEXT NOT NULL,
    kind TEXT NOT NULL,
    attributes TEXT DEFAULT '{}',
    confidence REAL DEFAULT 0.6,
    importance REAL DEFAULT 0.5,
    provenance TEXT DEFAULT '{}',
    created_at TEXT,
    updated_at TEXT,
    mentions INTEGER DEFAULT 1,
    merged_into TEXT DEFAULT '',
    UNIQUE(name_key, kind)
);
CREATE TABLE IF NOT EXISTS entity_aliases (
    entity_id TEXT NOT NULL,
    alias_key TEXT NOT NULL,
    PRIMARY KEY (entity_id, alias_key)
);
CREATE TABLE IF NOT EXISTS relations (
    id TEXT PRIMARY KEY,
    subject_id TEXT NOT NULL,
    predicate TEXT NOT NULL,
    object_id TEXT NOT NULL,
    confidence REAL DEFAULT 0.6,
    provenance TEXT DEFAULT '{}',
    created_at TEXT,
    updated_at TEXT,
    observations INTEGER DEFAULT 1,
    valid_from TEXT DEFAULT '',
    valid_to TEXT DEFAULT '',
    UNIQUE(subject_id, predicate, object_id)
);
CREATE TABLE IF NOT EXISTS beliefs (
    id TEXT PRIMARY KEY,
    entity_id TEXT NOT NULL,
    attribute TEXT NOT NULL,
    value TEXT,
    confidence REAL DEFAULT 0.6,
    provenance TEXT DEFAULT '{}',
    created_at TEXT,
    superseded_by TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_entities_kind ON entities(kind);
CREATE INDEX IF NOT EXISTS idx_relations_subject ON relations(subject_id);
CREATE INDEX IF NOT EXISTS idx_relations_object ON relations(object_id);
CREATE INDEX IF NOT EXISTS idx_beliefs_entity ON beliefs(entity_id, attribute);

-- natasha.approvals.engine
CREATE TABLE IF NOT EXISTS approval_requests (
    id          TEXT PRIMARY KEY,
    payload     TEXT NOT NULL,
    status      TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    mission_id  TEXT NOT NULL DEFAULT '',
    trace_id    TEXT NOT NULL DEFAULT '',
    fingerprint TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_approval_status ON approval_requests(status);
CREATE INDEX IF NOT EXISTS idx_approval_mission ON approval_requests(mission_id);

CREATE TABLE IF NOT EXISTS approval_tokens (
    id          TEXT PRIMARY KEY,
    request_id  TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    scope       TEXT NOT NULL DEFAULT '[]',
    token       TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    used_at     TEXT NOT NULL DEFAULT '',
    revoked     INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_token_request ON approval_tokens(request_id);

-- natasha.mcp.registry
CREATE TABLE IF NOT EXISTS mcp_servers (
    name TEXT PRIMARY KEY,
    transport TEXT NOT NULL,
    command TEXT DEFAULT '',
    args TEXT DEFAULT '[]',
    url TEXT DEFAULT '',
    env TEXT DEFAULT '{}',
    state TEXT NOT NULL,
    trust TEXT DEFAULT 'untrusted',
    permissions TEXT DEFAULT '[]',
    tools TEXT DEFAULT '[]',
    server_info TEXT DEFAULT '{}',
    installed_at TEXT DEFAULT '',
    last_seen TEXT DEFAULT '',
    enabled INTEGER DEFAULT 0,
    notes TEXT DEFAULT ''
);

-- natasha.credentials.vault
CREATE TABLE IF NOT EXISTS credentials (
    ref           TEXT PRIMARY KEY,
    kind          TEXT NOT NULL,
    provider      TEXT NOT NULL DEFAULT '',
    label         TEXT NOT NULL DEFAULT '',
    scopes        TEXT NOT NULL DEFAULT '[]',
    metadata      TEXT NOT NULL DEFAULT '{}',
    fingerprint   TEXT NOT NULL DEFAULT '',
    version       INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    rotated_at    TEXT NOT NULL DEFAULT '',
    last_used_at  TEXT NOT NULL DEFAULT '',
    expires_at    TEXT NOT NULL DEFAULT '',
    revoked       INTEGER NOT NULL DEFAULT 0,
    envelope      TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS credential_versions (
    id          TEXT PRIMARY KEY,
    ref         TEXT NOT NULL,
    version     INTEGER NOT NULL,
    envelope    TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    rotated_out INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cred_versions ON credential_versions(ref);

-- natasha.api.auth
CREATE TABLE IF NOT EXISTS owner (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    owner_id TEXT NOT NULL,
    salt BLOB NOT NULL,
    verifier BLOB NOT NULL,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_seen TEXT NOT NULL,
    expires_at REAL NOT NULL,
    client TEXT NOT NULL DEFAULT ''
);

-- shared runtime tables
CREATE TABLE IF NOT EXISTS natasha_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS affect_state (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    payload TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at TEXT NOT NULL,
    duration_ms REAL NOT NULL DEFAULT 0
);

-- down
-- Reverting the initial schema removes every Natasha table (data loss: this is a fresh-install rollback).

DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS relations;
DROP TABLE IF EXISTS owner;
DROP TABLE IF EXISTS natasha_meta;
DROP TABLE IF EXISTS missions;
DROP TABLE IF EXISTS memory_events;
DROP TABLE IF EXISTS memories;
DROP TABLE IF EXISTS mcp_servers;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS entity_aliases;
DROP TABLE IF EXISTS entities;
DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS credential_versions;
DROP TABLE IF EXISTS beliefs;
DROP TABLE IF EXISTS approval_tokens;
DROP TABLE IF EXISTS approval_requests;
DROP TABLE IF EXISTS affect_state;
