#!/usr/bin/env python3
"""Generate the initial migration files from the subsystems' own DDL.

Running this is how ``migrations/sqlite/0001_initial_schema.sql`` and its Postgres twin stay in step
with the code. The database layer test (`tests/unit/test_db_migrations.py`) applies the result to a
fresh database and asserts every table exists, so drift fails the suite rather than production.

    python3 scripts/generate_migrations.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from natasha.db.schema import collect_schema, render_postgres_schema, schema_tables  # noqa: E402

HEADER = """-- Natasha schema, generated by scripts/generate_migrations.py - do not edit by hand.
-- Source of truth: the SCHEMA constant of each subsystem (see natasha.db.schema).
"""

INDEXES = """
-- Query indexes for the hot paths: recent activity, mission lookup, recall, approval queue.
CREATE INDEX IF NOT EXISTS idx_events_kind_seq ON events(kind, seq DESC);
CREATE INDEX IF NOT EXISTS idx_events_mission ON events(mission_id, seq DESC);
CREATE INDEX IF NOT EXISTS idx_events_trace ON events(trace_id, seq DESC);
CREATE INDEX IF NOT EXISTS idx_events_risk ON events(risk, seq DESC);
CREATE INDEX IF NOT EXISTS idx_memories_kind ON memories(kind, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_missions_state ON missions(state, priority, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_approvals_status ON approval_requests(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mcp_servers_state ON mcp_servers(state, enabled);
"""

DROP_ALL = """
-- down
-- Reverting the initial schema removes every Natasha table (data loss: this is a fresh-install rollback).
"""


#: The runner owns its bookkeeping table: a schema rollback must not drop the record of itself.
RUNNER_OWNED = {"schema_migrations"}


def build_down(tables: list[str]) -> str:
    lines = [DROP_ALL.strip(), ""]
    for table in sorted(tables, reverse=True):
        if table in RUNNER_OWNED:
            continue
        lines.append(f"DROP TABLE IF EXISTS {table};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    sqlite_dir = ROOT / "migrations" / "sqlite"
    postgres_dir = ROOT / "migrations" / "postgres"
    sqlite_dir.mkdir(parents=True, exist_ok=True)
    postgres_dir.mkdir(parents=True, exist_ok=True)

    sqlite_schema = collect_schema()
    tables = schema_tables()
    (sqlite_dir / "0001_initial_schema.sql").write_text(
        HEADER + "\n" + sqlite_schema + "\n" + build_down(tables), encoding="utf-8")
    (sqlite_dir / "0002_indexes.sql").write_text(
        "-- Indexes for the hot query paths.\n" + INDEXES.strip() + "\n\n-- down\n"
        + "\n".join(f"DROP INDEX IF EXISTS {name};" for name in
                    ["idx_events_kind_seq", "idx_events_mission", "idx_events_trace", "idx_events_risk",
                     "idx_memories_kind", "idx_missions_state", "idx_approvals_status",
                     "idx_mcp_servers_state"]) + "\n",
        encoding="utf-8")

    try:
        postgres_schema = render_postgres_schema()
    except ValueError as exc:
        print(f"postgres translation needs manual work: {exc}", file=sys.stderr)
        return 1
    (postgres_dir / "0001_initial_schema.sql").write_text(
        HEADER + "-- Postgres translation (BIGSERIAL/BYTEA/DOUBLE PRECISION).\n\n"
        + postgres_schema + "\n" + build_down(tables), encoding="utf-8")

    print(f"wrote migrations for {len(tables)} tables: {', '.join(tables)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
